services:
  - type: web
    name: Test
    runtime: docker
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true

apiKey: rnd_hrT1CEhl7uCxLYzsr30DJGfUvWAH
